### ISSUE TITLE
Developer portal does not honor `xml: attribute: true` for examples

### ISSUE THREAD

**Issue by xakpc** [Azure/api-management-developer-portal#1104]
## Bug description

In my XML scheme, I define some properties as attributes by adding xml/attribute. This works fine and as expected
But if I add examples to these properties/attributes example generation ignore xml/attribute flag and generate them as properties, which is wrong and confusing.

I can bypass that by providing a pre-defined example though.

## Reproduction steps

Create a schema for XML like this one

```
components:
  schemas:
    Transition:
      required:
        - input
        - next
      type: object
      properties:
        input:
          example: "hello"
          type: string
          xml:
            attribute: true
        next:
          type: string
          xml:
            attribute: true
        morphology:
          example: msg memory
          type: string
          xml:
            attribute: true
```     

Add to any path
```
paths: 
  get: 
    responses:         
      '200':
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/Transition'
```

## Expected behavior
I expected generated based on OpenAPI 3 spec XML example (taken from https://editor.swagger.io/)
```
<?xml version="1.0" encoding="UTF-8"?>
<Transition input="hello" next="string" morphology="msg memory" >
</Transition>
```
but I get this instead
```
<Transition next="string">
      <input>hello</input>
      <morphology>msg memory</morphology>
</Transition>
```

## Is your portal managed or self-hosted?

Managed
