### ISSUE TITLE
Using Azure Static web apps to host APIM dev portal

### ISSUE THREAD

**Issue by restlessankyyy** [Azure/api-management-developer-portal#1598]
### Trying to deploy azure APIM dev portal using Github actions to Azure static web apps

Objective: To build and deploy APIM dev portal to azure static web apps using Github actions.

Github Actions in use: 
```
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 16.x
        uses: actions/checkout@v2
        with:
          node-version: 16.x
          
      - name: Install
        run: npm install
        
      - name: Build
        run: npm run build-website
          
      - name: Upload report artifact
        uses: actions/upload-artifact@v2
        with:
          name: accessibility-reports
          path: ${{ github.workspace }}/_accessibility-reports
deploy_job:
    runs-on: ubuntu-latest
    name: Deploy Job
    steps:
      - name: Deploy
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_BLA_BLA_BLA_BLA_ }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "/dist/website" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######


```

Issue: Deploy step throws an error

```
> DeploymentId: xxxxxx-xxxx-xxxx-xxxx-xxxxxxxx
> 
> App Directory Location: '/' was found.
> No Api directory specified. Azure Functions will not be created.
> Looking for event info
> The content server has rejected the request with: InternalServerError
> Reason: An unexpected error has occurred. Please try again later.
 
```
