### ISSUE TITLE
Default value for parameters not shown

### ISSUE THREAD

**Issue by nweseloh** [Azure/api-management-developer-portal#2341]
## Bug description

When a default value is specified for an operation, the default is not shown in the developer portal. 

## Reproduction steps

1. Import an OpenAPI definition like this (abbreviated): 

```
 /countries:
    get:
      operationId: get-countries
      parameters:
        - name: displayLanguage
          in: query
          description: Please provide a two letter language code to set the language for the display name.
          schema:
            type: string
            default: EN
          example: EN

```
2. Go to the developer portal and select the operation
3.  The 'default' value is not shown (only the 'example') value: 
![image](https://github.com/Azure/api-management-developer-portal/assets/1902260/93ffaf41-03b4-4868-9793-c7ec1a4dd731)

## Expected behavior
The 'default' value should be shown, similar to the example value, like this: 

![image](https://github.com/Azure/api-management-developer-portal/assets/1902260/bb75b176-61b7-46cf-a34f-3c9369c2ede8)

## Is your portal managed or self-hosted?

Managed
